### ISSUE TITLE
SCUC_DC.m中支路潮流约束可能存在问题

### ISSUE THREAD

**Issue by breeze-zhaofei** [Wang-Yanping1996/Secured-Constraints-Unit-Commitment-SCUC-model-of-Power-system#5]
您好，
SCUC_DC.m中支路潮流约束（228行左右）可能存在问题
%潮流方程
% 支路潮流约束
for t = 1: n_T
    C = [C,
        PF_D(:, t) == Bf*Va(:, t) + Pfinj,
        ];
end
按照makeBdc.m中的说明，PF_D(:, t)计算的 是线路始端bus的功率注入，这样和下面的程序中PF_D(branch(:, T_BUS) == i 可能有所矛盾
%节点功率平衡约束
for t = 1: n_T
    for i = 1: n_bus
        C = [C,
            gen_P(i,t) == Pd(i,t) + ...
                          sum(PF_D(branch(:, F_BUS) == i,t)) - ...
                          sum(PF_D(branch(:, T_BUS) == i,t)) + ...
                          bus(i, BUS_GS)/baseMVA,
            ];
    end
end

根据matpower手册，DCOP的支路潮流约束和节点功率平衡约束只需要手册中的式（3.32）表示即可。

以上是一点疑问，可能不正确，欢迎讨论。

**Comment by hongfangao** [comment]
> 通常在计算直流潮流的时候，认为简化后的直流模型中，线路始端和末端的功率是一致的（参考matpower手册3.29下面的话），那么PF_D(branch(:, T_BUS) == i) 可以准确表示各条支路流入母线i的功率。

不采用表达式（3.32）的原因，主要在于我们需要支路功率PF_D 来构建安全约束 PF_D <= Fmax，当然也可以写成（3.32）的形式，不过根据我的测试，结果应当是一致的（目前不计入Gsh的影响）。

**Comment by Wang-Yanping1996** [comment]
通常在计算直流潮流的时候，认为简化后的直流模型中，线路始端和末端的功率是一致的（参考matpower手册3.29下面的话），那么PF_D(branch(:, T_BUS) == i) 可以准确表示各条支路流入母线i的功率。

不采用表达式（3.32）的原因，主要在于我们需要支路功率PF_D 来构建安全约束 PF_D <= Fmax，当然也可以写成（3.32）的形式，不过根据我的测试，结果应当是一致的（目前不计入Gsh的影响）。
